# Generated by Django 5.1.2 on 2024-11-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListedIPAddresses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
            ],
            options={
                "verbose_name": "Black Listed IP Address",
                "verbose_name_plural": "Black Listed IP Addresses",
            },
        ),
    ]
